CREATE DATABASE IF NOT EXISTS Mercado;

USE Mercado;

CREATE TABLE IF NOT EXISTS CLIENTE (
    ID_CLIENTE INT NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
    nombre_cliente VARCHAR(30) NOT NULL,
    telefono VARCHAR(10) NULL, UNIQUE,
    direccion VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS PRODUCTO (
    ID_PRODUCTO INT NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(30) NOT NULL,
    precio FLOAT NOT NULL,
    descripcion_producto VARCHAR(100),
	foto_producto VARCHAR(80) NOT NULL UNIQUE DEFAULT 'imagen-generica.jpg',
    Peso VARCHAR(10) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS FACTURA (
    ID_FACTURA INT NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
    ID_CLIENTE INT NOT NULL,
    Precio FLOAT NOT NULL,
    Costo_envio FLOAT NOT NULL,
    ID_DELIVERY INT NOT NULL,
    Descuento FLOAT NOT NULL,
    Total FLOAT NOT NULL,
      FOREIGN KEY (ID_CLIENTE)
        REFERENCES clientes(ID_CLIENTE)
        ON DELETE CASCADE
        ON UPDATE CASCADE
    );
    
    CREATE TABLE IF NOT EXISTS VENTA (
    ID_VENTA INT NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
    ID_FACTURA INT NOT NULL UNIQUE,
    ID_PRODUCTO INT NOT NULL UNIQUE,
    Fecha de Venta DATE NOT NULL,
    Cantidad INT(50) NOT NULL,
    Sub Total FLOAT NOT NULL,
      FOREIGN KEY (ID_FACTURA)
        REFERENCES FACTURA(ID_FACTURA)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY (ID_PRODUCTO)
        REFERENCES PRODUCTO(ID_PRODUCTO)
        ON DELETE CASCADE
        ON UPDATE CASCADE
    );
    
    CREATE TABLE IF NOT EXISTS STOCK (
    ID_PROVEEDOR INT NOT NULL UNIQUE,
    ID_PRODUCTO INT(20) NOT NULL UNIQUE,
    Nombre del producto VARCHAR NOT NULL,
    Cantidad INT NOT NULL,
    Medida INT NOT NULL,
    Stock_minimo FLOAT NOT NULL,
      FOREIGN KEY (ID_PROVEEDOR)
        REFERENCES PROVEEDOR(ID_PROVEEDOR)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY (ID_PRODUCTO)
        REFERENCES PRODUCTO(ID_PRODUCTO)
        ON DELETE CASCADE
        ON UPDATE CASCADE
    );
    
    CREATE TABLE IF NOT EXISTS INGREDIENTES (
    ID_INGREDIENTES INT NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
    ID_PRODUCTO INT(20) NOT NULL,
    Cantidad FLOAT NOT NULL,
    FOREIGN KEY (ID_PRODUCTO)
    REFERENCES PRODUCTO(ID_PRODUCTO)
    ON DELETE CASCADE
    ON UPDATE CASCADE
    );
    
    CREATE TABLE IF NOT EXISTS COMPRA (
    Numero de compra INT NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
    ID_PROVEEDOR INT(20) NOT NULL UNIQUE,
    ID_PRODUCTO INT NOT NULL UNIQUE,
    Cantidad de compra INT NOT NULL,
    FOREIGN KEY (ID_PROVEEDOR)
    REFERENCES PROVEEDOR(ID_PROVEEDOR)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    FOREIGN KEY (ID_PRODUCTO)
    REFERENCES PRODUCTO(ID_PRODUCTO)
    ON DELETE CASCADE
    ON UPDATE CASCADE
        );
        
   CREATE TABLE IF NOT EXISTS DELIVERY (
   ID_DELIVERY INT NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
   Nombre VARCHAR(30) NOT NULL,
   Apellido VARCHAR(30) NOT NULL,
   Email VARCHAR(30) NULL UNIQUE,
   Telefono INT(10) NULL UNIQUE,
   Direccion VARCHAR(50) NULL UNIQUE,
   Vehiculo INT(50) NULL UNIQUE,
   Patente INT(10) NULL UNIQUE
   );
   
   CREATE TABLE IF NOT EXISTS METODO DE PAGO (
   ID_METODOPAGO INT NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
   Forma de pago VARCHAR(50) NOT NULL.
   Entidad VARCHAR(50) NOT NULL UNIQUE
   );
   
   CREATE TABLE IF NOT EXISTS DESCUENTOS (
   ID_DESCUENTO INT NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
   Nombredescuento FLOAT(10) NOT NULL UNIQUE,
   Valordescuento VARCHAR(40) NOT NULL UNIQUE,
   ID_FACTURA INT NOT NULL UNIQUE,
   ID_CLIENTE INT NOT NULL UNIQUE,
   FOREIGN KEY (ID_FACTURA),
   REFERENCES FACTURA(ID_FACTURA)
   ON DELETE CASCADE
   ON UPDATE CASCADE,
   FOREIGN KEY (ID_CLIENTE)
   REFERENCES CLIENTE(ID_CLIENTE)
   ON DELETE CASCADE 
   ON UPDATE CASCADE
   );
   
   CREATE TABLE IF NOT EXISTS EMPLEADOS(
   ID_EMPLEADOS INT NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
   Nombre VARCHAR(30) NOT NULL,
   Apellido VARCHAR(30) NOT NULL,
   Telefono_empleado INT(10) NOT NULL UNIQUE,
   Email_empleado VARCHAR(30) NOT NULL UNIQUE
   );
   
   CREATE TABLE IF NOT EXISTS EXPERIENCIA DEL CLIENTE (
   ID_EXPERIENCIA INT NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
   Fecha_comentario DATE NOT NULL,
   Comentario VARCHAR(300) NULL,
   Calificacion INT(10) NULL,
   ID_CLIENTE INT NOT NULL UNIQUE,
   FOREIGN KEY(ID_CLIENTE)
   REFERENCES CLIENTE(ID_CLIENTE)
   ON DELETE CASCADE
   ON UPDATE CASCADE
   );
   
   
    
    